services:
  db:
    image:  mysql:8.0.34
    container_name: main-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: oz
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root