# Generated by Django 5.1.3 on 2024-11-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("planner_id", models.BigIntegerField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "calendars",
            },
        ),
    ]
