# Generated by Django 5.1.3 on 2024-11-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                ("login_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("login_at", models.DateTimeField(auto_now_add=True)),
                ("logout_at", models.DateTimeField(auto_now_add=True)),
                ("user_ip", models.CharField(max_length=50)),
                ("user_agent", models.TextField()),
                ("is_success", models.BooleanField(default=True)),
            ],
        ),
    ]
